name = "cifar10_extensive"

[dataset]
name = "cifar10"
root = "./data"
download = true

[trainer]
epochs = 30
batch_size = 128
eval_batch_size = 256
num_workers = 4
learning_rate = 0.0005
seed = 1337
deterministic = false

[optics.noise]
enabled = true
sigma = 0.1
sigma_range = [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6]

[optics.quant]
enabled = true
bits = 8
bits_range = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
per_channel = true
per_channel_options = [false, true]

[optics.drift]
enabled = true
sigma = 0.001
theta = 0.002
sigma_range = [0.0, 0.0002, 0.0004, 0.0006, 0.0008, 0.001, 0.0012, 0.0014, 0.0016, 0.0018, 0.002]
theta_range = [0.0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.01]

[optics.complex]
enabled = false

[logging]
output_dir = "./runs/cifar"
save_curves = true
save_confusion = true
save_metrics = true
