name = "fashion_mnist_extensive"

[dataset]
name = "fashion_mnist"
root = "./data"
download = true

[trainer]
epochs = 20
batch_size = 128
eval_batch_size = 256
num_workers = 4
learning_rate = 0.001
seed = 2112
deterministic = false

[optics.noise]
enabled = true
sigma = 0.1
sigma_range = [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6]

[optics.quant]
enabled = true
bits = 8
bits_range = [2, 3, 4, 5, 6, 7, 8, 9, 10]
per_channel = false
per_channel_options = [false, true]

[optics.drift]
enabled = true
sigma = 0.0005
theta = 0.0
sigma_range = [0.0, 0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008, 0.0009, 0.001]
theta_range = [0.0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.01]

[optics.complex]
enabled = false

[logging]
output_dir = "./runs/fashion"
save_curves = true
save_confusion = true
save_metrics = true
